objects/Candidate__c.object
<CustomObject>
    <description>Represents an applicant who might apply for one or more positions</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <externalId>true</externalId>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <externalId>true</externalId>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Candidate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CustomCandidateController.cls
public class CustomCandidateController {
	@RemoteAction
	public static List<Candidate__c> getListCandidates ( String searchText ) {
		String searchString              = '%' + searchText + '%';
		List<Candidate__c> listCandidate = [SELECT Id, City__c, First_Name__c, Last_Name__c FROM Candidate__c WHERE First_Name__c LIKE :searchString];
		return listCandidate;
	}

	@RemoteAction
	public static List<Candidate__c> removeCandidate ( Id id, String searchText ) {
		Candidate__c c = [SELECT First_Name__c FROM Candidate__c WHERE Id =: id];
		delete c;
		return getListCandidates( searchText );
	}
}