objects/Candidate__c.object
<CustomObject>
    <description>Represents an applicant who might apply for one or more positions</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <externalId>true</externalId>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <externalId>true</externalId>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <label>State/Province</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Candidate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CandidateRegister.cls
public with sharing class CandidateRegister {
    String firstName { set; get; }

    public CandidateRegister ( ApexPages.StandardController stdController ) {}

    @RemoteAction
    public static String toRegister ( String firstName,
                                      String lastName,
                                      String email,
                                      String phone,
                                      String street,
                                      String city,
                                      String stateProvince ) {
        Candidate__c candidate      = new Candidate__c();

        candidate.First_Name__c     = firstName;
        candidate.Last_Name__c      = lastName;
        candidate.Email__c          = email;
        candidate.Phone__c          = phone;
        candidate.Street__c         = street;
        candidate.City__c           = city;
        candidate.State_Province__c = stateProvince;

        try {
            insert candidate;
        } catch ( Exception ex ) {
            return ex.getMessage();
        }

        return firstName;
    }
}